### PR TITLE
make it faster and avoid run time allocations

### PR DESCRIPTION
**Pull request by u2**
Inspired by [avoid run time allocations](https://github.com/wonderbread/rack-pratchett/commit/dcbe15d604f5464fa64f775f411598d81d61c1df), and [fasterer] (https://github.com/DamirSvrtan/fasterer)

### CODE REVIEW

**Comment by dm1try** [comment]
@u2 interesting, should we add a CHANGELOG entry with `ips` results? :smile:
I mean is it worth it? (especially wonder about time allocations, is overhead huge?)

**Comment by dblock** [comment]
Very interesting. I am going to merge this, the code looks good. It's pretty obvious that those are "better", but I would love to hear how much better, @u2? Any benchmarks?

**Comment by u2** [comment]
Here are some benchmarks from [fast-ruby](https://github.com/JuanitoFatas/fast-ruby).

##### `Hash#merge!` vs `Hash#[]=` [code](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/hash/merge-bang-vs-\[\]=.rb)

```
$ ruby -v code/hash/merge-bang-vs-\[\]=.rb
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

Calculating -------------------------------------
         Hash#merge!     1.023k i/100ms
            Hash#[]=     2.844k i/100ms
-------------------------------------------------
         Hash#merge!     10.653k (± 4.9%) i/s -     53.196k
            Hash#[]=     28.287k (±12.4%) i/s -    142.200k

Comparison:
            Hash#[]=:    28287.1 i/s
         Hash#merge!:    10653.3 i/s - 2.66x slower
```


##### `String#gsub` vs `String#tr` [code](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/string/gsub-vs-tr.rb)

> [rails/rails#17257](https://github.com/rails/rails/pull/17257)

```
$ ruby -v code/string/gsub-vs-tr.rb
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

Calculating -------------------------------------
         String#gsub    38.268k i/100ms
           String#tr    83.210k i/100ms
-------------------------------------------------
         String#gsub    516.604k (± 4.4%) i/s -      2.602M
           String#tr      1.862M (± 4.0%) i/s -      9.320M

Comparison:
           String#tr:  1861860.4 i/s
         String#gsub:   516604.2 i/s - 3.60x slower
```


##### `Enumerable#reverse.each` vs `Enumerable#reverse_each` [code](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/enumerable/reverse-each-vs-reverse_each.rb)

> `Enumerable#reverse` allocates an extra array.  <br>
> `Enumerable#reverse_each` yields each value without allocating an extra array. <br>
> This is the reason why `Enumerable#reverse_each` exists. <br>
> -- @sferik [rails/rails#17244](https://github.com/rails/rails/pull/17244)

```
$ ruby -v code/enumerable/reverse-each-vs-reverse_each.rb
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

Calculating -------------------------------------
  Array#reverse.each    16.746k i/100ms
  Array#reverse_each    18.590k i/100ms
-------------------------------------------------
  Array#reverse.each    190.729k (± 4.8%) i/s -    954.522k
  Array#reverse_each    216.060k (± 4.3%) i/s -      1.078M

Comparison:
  Array#reverse_each:   216060.5 i/s
  Array#reverse.each:   190729.1 i/s - 1.13x slower
```

I have run these already, they more or less match the result of `fast-ruby`

**Comment by u2** [comment]
The time allocations is slight difference.

```ruby
require 'benchmark/ips'

def slow(env)
  status, headers, body = env
  headers.delete('Http-Access-Token')
  [status, headers, body]
end

def fast(env)
  env[1].delete('Http-Access-Token')
  env
end

env = [200, { 'Http-Access-Token' => '99d25f556b456d658ba0185540d9daa0' }, 'Hello ips']

Benchmark.ips do |x|
  x.report('slow Assignment') { slow(env) }
  x.report('fast Assignment') { fast(env) }
  x.compare!
end

def slow_ext(env)
  status, headers, body = env
  headers['X-Clacks-Overhead'] = 'GNU Terry Pratchett'
  [status, headers, body]
end

def fast_ext(env)
  env[1]['X-Clacks-Overhead'.freeze] = 'GNU Terry Pratchett'.freeze
  env
end

env = [200, { 'Http-Access-Token' => '99d25f556b456d658ba0185540d9daa0', 'X-Cascade' => 'Cascade' }, 'Hello ips']

Benchmark.ips do |x|
  x.report('slow Assignment') { slow_ext(env) }
  x.report('fast Assignment') { fast_ext(env) }
  x.compare!
end
```

```
ruby -v code/general/assignment_array.rb
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
Calculating -------------------------------------
     slow Assignment    82.656k i/100ms
     fast Assignment    85.914k i/100ms
-------------------------------------------------
     slow Assignment      2.444M (± 7.7%) i/s -     12.150M
     fast Assignment      2.997M (± 7.5%) i/s -     14.949M

Comparison:
     fast Assignment:  2997189.9 i/s
     slow Assignment:  2443517.4 i/s - 1.23x slower

Calculating -------------------------------------
     slow Assignment    80.723k i/100ms
     fast Assignment   101.598k i/100ms
-------------------------------------------------
     slow Assignment      2.457M (± 7.0%) i/s -     12.270M
     fast Assignment      3.957M (± 7.9%) i/s -     19.710M

Comparison:
     fast Assignment:  3957163.9 i/s
     slow Assignment:  2457315.4 i/s - 1.61x slower
```

**Pull request merged**
