### PR TITLE
Fix for #881

### PR DESCRIPTION
**Pull request by ajvondrak**
I added some regression tests and avoid `to_a`-ing the `Range` at all. What do you think?

### CODE REVIEW

**Comment by dblock** [comment]
This is good. You have to look at CI failures on those other platforms (we do support them :)) and squash the commits please.

**Comment by ajvondrak** [comment]
Woops, hadn't noticed the build failing. :) Ruby 1.9.3 doesn't have a `Range#size` method, as it turns out.

Anyway, fixed (assuming Travis says so) & squashed.

**Comment by dblock** [comment]
Thanks, merging.

**Comment by u2** [comment]
:+1:

**Pull request merged**
