### PR TITLE
Add SplitValidator

### PR DESCRIPTION
**Pull request by u2**
https://gist.github.com/jordansexton/260662acf75e66d9bf79

### CODE REVIEW

**Comment by dblock** [comment]
This is a very esoteric validator, frankly I am against merging it. Why would we encourage anyone to pass data this way when URI parsing supports arrays?

**Comment by u2** [comment]
Yes, I agree about that.

**Comment by dm1try** [comment]
For me it's not a validator. We already have two "special validators" that can modify the params(`coerce` and `default`) but I don't really like that.

**Comment by dblock** [comment]
I am closing this without merging, thanks for your suggestion @u2!

**Pull request closed without merging**
