### PR TITLE
Allows values to be a kind of the coerced type in range

### PR DESCRIPTION
**Pull request by u2**
My code like this ```requires :month, type: Integer, values: 1..12``, the Range values coercion is workable.Before it workable, now it failed.

https://github.com/u2/grape/commit/0df3bda5d288d03d1647170ab2cbcb645001a324#diff-45b62b4ed0aed7ceff346c347f76570e

After ```!(@values.is_a?(Proc) ? @values.call : @values).include?(params[attr_name])``` chang to ```(param_array - values).empty?```, the Range values coercion raise a error ```no implicit conversion of Range into Array```

### CODE REVIEW

**Comment by dblock** [comment]
I think we should just support `Range` explicitly with code that looks at `values` and says "are you a range, if so do this ...". As you pointed out having a big range would make a side effect of converting it to an array every time, which can't be good ;)

This will need a CHANGELOG entry and a note in the README that `Range` is explicitly supported as a type.

**Comment by dblock** [comment]
This is https://github.com/intridea/grape/issues/881.

**Comment by u2** [comment]
I think it's easy check a value in a Range or not.But it's not easy check the array params in a Range or not, unless converting it to an array every time.

**Comment by dblock** [comment]
Can we make this lazier though? At least half of the use-case is not an Array/Range scenario.

**Comment by ajvondrak** [comment]
BTW, I think this can be closed since https://github.com/intridea/grape/pull/899 was merged.

**Comment by u2** [comment]
Thanks.

**Comment by dblock** [comment]
Thanks, closing.

**Pull request closed without merging**
