### PR TITLE
Only dup InheritableValues, remove support for deep_dup

### LINKED ISSUE #891: Cloned InheritableSetting seems to clone unnecessary stuff
#739 creates a `point_in_time_copy` of route configuration. It `deep_dup`s everything in the hash, including classes. Problem is:

```ruby
desc "...", {
  entity: ArticlePresenter
}
```

The `ArticlePresenter` class is also getting `deep_dup`ed, which produces a `#<Class:0x...>` which leads to problems with equality and also not copying all class methods. It doesn't play nice with grape-swagger in some cases.

Currently I solved it by adding

```ruby
class Grape::Entity
  def self.deep_dup
    self
  end
end
```

I think I understand the need to make a current copy, but do you think it's OK to take out classes from the `deep_dup`?

### PR DESCRIPTION
**Pull request by toddmazierski**
## Summary

To fix #891, settings managed with `InheritableValues` are now `dup`ed instead of `deep_dup`ed. This is a continuation of the change made in #1034 for `StackableValues`, and the same notes on impact and testing (ex. trying this out in real projects) likely apply!

## Other Changes

Now that `deep_dup` is no longer used, support for it has been removed (`lib/backports`).

## Related Issues

* #873 / #1038

### CODE REVIEW

**Comment by dblock** [comment]
Thanks, can you please squash these commits?

**Comment by toddmazierski** [comment]
> Thanks, can you please squash these commits? 

Done (bdb334c3aa73533f6aedba177913e26de616f1f8)! The Travis build appears to be stuck, though.

**Comment by dblock** [comment]
Merged, thank you.

**Comment by toddmazierski** [comment]
You're welcome. Thanks for your help, and all your hard work on Grape!

**Pull request merged**
